name: Backend Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Buildx va Multi-platformali qurish uchun zarur
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # V3 versiyasiga yangilandi
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # BIRLASHTIRILGAN QADAM: Build, Tag va Push (Bitta Qadamda)
      - name: Build and push Multi-platform Docker image
        # Run buyrug'ida multi-platformali qurish uchun kerakli barcha parametrlar mavjud.
        # '--push' qo'shilgani uchun alohida 'docker push' qadamiga ehtiyoj qolmaydi.
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/cyber-shop-pro-backend:latest
          
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME \
            --push \
            . # Bu nuqta (Context Path) argumenti juda muhim!